---
name: Cache-Weak
version: 1.0.2
author:
  - 'Eugen Sobchenko <ejs@cpan.org>'
abstract: weak reference cache
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Scalar::Util: 1.14
  Test::More: 0.47
  perl: 5.6.1
  version: 0.50
provides:
  Cache::Weak:
    file: lib/Cache/Weak.pm
    version: 1.0.2
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
